### ISSUE TITLE
Support for timestamps submitted as floats

### ISSUE THREAD

**Issue by supernullset** [kissmetrics/py-KISSmetrics#26]
From Dylan:
"
Currently, if someone using the Python library (and potentially other libraries) tries to send in a float as a timestamp, it gets converted to something like 1426982400.0. This doesn't generate any errors, and it shows up in the live tab just fine, but any events recorded with this timestamp won't be properly processed and won't show up in a user's account.
"

**Comment by ewdurbin** [comment]
version 1.0.1 released to PyPI

**Comment by supernullset** [comment]
:bee: :honey_pot: for everyone!
